{% set name = "i18nice" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/i18nice-{{ version }}.tar.gz
  sha256: 5b72b3030f4937706604d7e42194ec57a6d71e989c6ce3802770c35ed6c75803

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - i18n
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Krutyi-4el/i18nice
  summary: Translation library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cmarmo
