{% set name = "i18nice" %}
{% set version = "0.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/i18nice-{{ version }}.tar.gz
  sha256: f9b770abcd381f2b13cff538e1938251f10fcedf8ff75828a3ce933c55c7e8ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - i18n
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/solaluset/i18nice
  summary: Translation library for Python
  description: |
    This library provides i18n functionality for Python 3 out of the box.
    The usage is mostly based on Rails i18n library.
    See https://github.com/solaluset/i18nice for details.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cmarmo
